version: '3.8'

services:
  web:
    build: .
    container_name: image_crypto
    ports:
      - "5000:5000"
    volumes:
      - ./static/uploads:/app/static/uploads
    environment:
      - FLASK_ENV=production
    restart: unless-stopped